spring.application.name=GestionMaMi
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=randrianomentsoasafidy@gmail.com
spring.mail.password=vxkxiluoyzopdgtj
app.admin.email=mangoromiray@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true